version: "2.0"
services:
  tic-api:
    build: .
    ports:
      - "3050:3050"
    links:
      - tic-db
  tic-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=notUser
      - MONGO_INITDB_ROOT_PASSWORD=notPassword
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

# docker compose up