# Use an official Node.js, and it should be version 16 and above
FROM node:20-alpine
# Set the working directory in the container
WORKDIR /home/app
# Copy package.json and pnpm-lock.yaml
COPY pnpm-lock.yaml package.json ./
# Install app dependencies using PNPM
RUN npm install -g pnpm
# Install dependencies
RUN pnpm i 

RUN pnpm i nodemon 
# Copy the application code 
COPY . .
# Expose the app
EXPOSE 3050
# Start the application
CMD ["pnpm", "dev"]