version: "2.0"
services:
  tic-db-test:
    image: mongo
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=notUser
      - MONGO_INITDB_ROOT_PASSWORD=notPassword
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

    # docker compose -f docker-compose-test.yml up
