name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: ${{ matrix.mongodb-version }}
      - name: npm install
        run: |
          npm install -g pnpm
      - name: pnpm install
        run: |
          pnpm install
      - name: pnpm run build
        run: |
          pnpm run build
      - name: pnpm run test unit
        run: |
          pnpm run test:unit
      - name: pnpm run test e2e
        run: |
          pnpm run test:api